pipeline {
    agent any

    environment {
        AWS_REGION = "ap-south-1"
        ECR_REPO   = "484907483770.dkr.ecr.ap-south-1.amazonaws.com/myapp"
        IMAGE_TAG  = "build-${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/javeriya01/javaapp.git'
            }
        }

        stage('Build with Maven') {
            steps {
                dir('javaapp/myapp') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }


        stage('Docker Build & Push') {
            steps {
                script {
                    dir('javaapp/myapp') {
                        sh """
                        docker build -t myapp:${IMAGE_TAG} .
                        docker tag myapp:${IMAGE_TAG} $ECR_REPO:${IMAGE_TAG}
                        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO
                        docker push $ECR_REPO:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage('Deploy to EKS') {
            steps {
                script {
                    dir('javaapp/myapp') {
                        sh """
                        # Update deployment image before applying
                        kubectl set image deployment/myapp-deployment myapp=$ECR_REPO:${IMAGE_TAG} --record || true
                        kubectl apply -f deployment.yaml
                        kubectl apply -f service.yaml
                        kubectl apply -f hpa.yaml
                        """
                    }
                }
            }
        }
    }
}
