pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/javeriya01/javaapp.git'
            }
        }

        stage('Check Minikube') {
            steps {
                sh '''
                    # Check if minikube is running, otherwise start it
                    if ! minikube status >/dev/null 2>&1; then
                        echo "Starting Minikube..."
                        minikube start --driver=docker
                    else
                        echo "Minikube is already running."
                    fi
                    
                    # Fix kubectl context for Jenkins
                    minikube update-context
                    
                    # Fix TLS certificate issue
                    kubectl config set-cluster minikube --insecure-skip-tls-verify=true
                    
                    # Test connection
                    kubectl get nodes
                '''
            }
        }

        stage('Build with Maven') {
            steps {
                dir('myapp') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('myapp') {
                    sh '''
                        # Point Docker to Minikube
                        eval $(minikube -p minikube docker-env)
                        docker build -t myapp:latest .
                    '''
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                dir('myapp') {
                    sh '''
                        kubectl apply -f deployment.yaml
                        kubectl apply -f service.yaml
                        kubectl apply -f hpa.yaml
                        kubectl get all
                    '''
                }
            }
        }
    }
}
