apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
